### ISSUE TITLE
Bug in mercurial backend

### ISSUE THREAD

**Issue by stucchio** [alex/pyvcs#2]
To reproduce, create a mercurial repository, then try to get the file '' _without_ selecting a revision, and you'll get a very confusing error. To reproduce, try the following:

r = get_backend('hg').Repository("REPODIR")
r.file_contents(u'', '0') #Will raise a FileDoesNotExist error.
r.file_contents(u'', None) #Will raise an hg.util.Abort error.

The problem occurs in the 'return fctx.data()' line of hg.py. Putting this into a try block which catches the hg.util.Abort error and raising a FileDoesNotExist error fixes this.

My branch incorporates this fix: http://github.com/stucchio/pyvcs/tree/master

**Comment by alex** [comment]
Fixed (forgot to credit you in the commit :( )

**Comment by alex** [comment]
Erm, close damnit!

**Comment by alex** [comment]
Fixed?

**Comment by stucchio** [comment]
Only partially. 

The real problem is that repo.changectx(None) returns a workingctx rather than a changectx. This is a context representing the "working directory", and it behaves oddly in several cases. 

However, I think that pyvcs really wants to return the 'tip' (much like the svn 'head') rather than the working directory. This appears to be what the svn backend does, though I don't fully understand that code.

My branch makes it do this.

Also, I discovered a bug in the list_directory function. If the dir doesn't exist,  the function raises no FolderDoesNotExist exception. This is also fixed in my branch.

**Comment by alex** [comment]
I can't seem to figure out how to reopen a ticket, so can you please open a new one and I'll ping Justin about it (he did the Hg support).
