### ISSUE TITLE
Mercurial backend returns None rather than empty list when no recent commits

### ISSUE THREAD

**Issue by joshourisman** [alex/pyvcs#7]
With the other backends, a repo.get_recent_commits() returns an empty list if there are no recent commits, however the mercurial backend returns None. This inconsistency can cause problems if a list is expected (for example in piano-man the timeline view requires an iterable and therefore fails when it gets None).

I've got a commit that fixes this: http://github.com/joshourisman/pyvcs/commit/525791f9a40baee1a91f4367a390c2122224cdd4

**Comment by alex** [comment]
Fixed
