### ISSUE TITLE
Tags cause error with git backend

### ISSUE THREAD

**Issue by joshourisman** [alex/pyvcs#8]
Currently the Repository.get_recent_commits method for the git backend attempts to fetch the commit trees for all refs in the repository. This is a problem, because there are refs for things that are not commits, such as tags (try using it with the pyvcs repo for a demonstration).

I see two possible resolutions to this depending on desired behavior:
1. use all the refs in the repo, but skip any that aren't commits
2. rather than using all the refs in the repo, only use head

I have changesets for either approach.
Approach 1:
    diff --git a/pyvcs/backends/git.py b/pyvcs/backends/git.py
    index 1e2f282..3a36cd7 100644
    --- a/pyvcs/backends/git.py
    +++ b/pyvcs/backends/git.py
    @@ -93,8 +93,8 @@ class Repository(BaseRepository):
                 head = pending_commits.pop(0)
                 try:
                     commit = self._repo.commit(head)
    -            except KeyError:
    -                raise CommitDoesNotExist
    +            except:
    +                continue
                 if commit.id in history or datetime.fromtimestamp(commit.commit_time) <= since:
                     continue
                 history[commit.id] = commit

Approach 2:
    diff --git a/pyvcs/backends/git.py b/pyvcs/backends/git.py
    index 1e2f282..b44db00 100644
    --- a/pyvcs/backends/git.py
    +++ b/pyvcs/backends/git.py
    @@ -85,9 +85,10 @@ class Repository(BaseRepository):
                 lambda: generate_unified_diff(self, files, commit.parents[0], commit.id))

```
     def get_recent_commits(self, since=None):
+        head = self._repo.head()
         if since is None:
-            since = datetime.fromtimestamp(self._repo.commit(self._repo.head()).commit_time) - timedelta(days=5)
-        pending_commits = self._repo.get_refs().values()#[self._repo.head()]
+            since = datetime.fromtimestamp(self._repo.commit(head).commit_time) - timedelta(days=5)
+        pending_commits = [head]
         history = {}
         while pending_commits:
             head = pending_commits.pop(0)
```

**Comment by alex** [comment]
Closed by ed5f3f833bdfdc3e08ff2813dc2e6578f7f0b51f.  the git backend will no longer raise an exception on Tags.
